version: "3.8"

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app  # Syncs local code changes with the container
    restart: always
