version: "3.8"

services:
  flask-app:
    build: .
    ports:
      - "5007:5007"
    env_file:
      - .env
    volumes:
      - .:/app  # Syncs local code changes with the container
      - /var/run/docker.sock:/var/run/docker.sock  # Allows Docker commands inside the container
      - /var/run/docker:/var/run/docker
    restart: always
